name: build
on: 
  push:
    paths:
      - '**.js'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [16, 18]
        exclude:
          - os: macos-latest
            node: 18
    steps:
      - name: Use node.js ${{ matrix.node }}
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@1
        with: 
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build --if-present