name: build
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest]
        node: [16]
        # exclude:
        #   - os: macos-latest
        #     node: 18
    steps:
      - name: My first step
        env: 
          MY_VAR: Hi there! my name is
          FIRST_NAME: Lakeside
          LAST_NAME: Smith
        run: |
          echo $MY_VAR
          echo $FIRST_NAME
          echo $LAST_NAME
      - name: My second step
        if: success()
        run: echo "The previous step has finished successfully"
      - name: Use node.js ${{ matrix.node }}
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com/
      - name: My fourth step
        uses: actions/first-interaction@v1
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Message that will be displayed on users first issue"
          pr-message: "Message that will be displayed on user first pr"
      - run: npm ci
      - run: npm run build --if-present